---
- name: OSX Local Provisioner
  hosts: local
  sudo: no
  pre_tasks:
    - stat: path=~/.ssh
      register: ssh 
  roles:
    # App Installations
    - brew
    - defaults
      #    - brew-cask
      #
      #    # Configurations
      #    - git
      #    - vim
      #    - xcode
      #    - zsh
      #    - {
      #      role: ssh,
      #      when: not ssh.stat.exists
      #    }
